server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  #  security:
  #    user:
  #      name: ebul
  #      password: ebul

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      '[hibernate.format_sql]': true
logging:
  file:
    name: logs/studentapp.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"